In [2]:
import pandas as pd

In [5]:
df = pd.read_csv('../raw_data/Covid_Data/germany_covid_data.csv', sep=",")
df

,time_iso8601,DE-BB,DE-BE,DE-BW,DE-BY,DE-HB,DE-HE,DE-HH,DE-MV,DE-NI,DE-NW,DE-RP,DE-SH,DE-SL,DE-SN,DE-ST,DE-TH,sum_deaths
0,2020-03-02T17:00:00+0000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,2020-03-03T17:00:00+0000,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,2020-03-04T17:00:00+0000,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,2
3,2020-03-05T17:00:00+0000,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,3
4,2020-03-06T17:00:00+0000,0,0,3,1,0,0,1,0,0,2,0,0,0,0,0,0,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1056,2023-01-22T17:00:00+0000,6424,5419,18912,28027,951,12115,3503,2730,13029,30725,6796,3432,2070,16717,6217,8211,165278
1057,2023-01-23T17:00:00+0000,6424,5421,18916,28030,951,12116,3504,2731,13033,30729,6799,3432,2071,16717,6218,8212,165304
1058,2023-01-24T17:00:00+0000,6424,5421,18916,28030,951,12117,3505,2731,13034,30730,6800,3433,2071,16717,6218,8212,165310
1059,2023-01-25T17:00:00+0000,6424,5421,18917,28030,951,12118,3505,2731,13034,30730,6800,3434,2071,16717,6218,8212,165313
1060,2023-01-26T17:00:00+0000,6424,5421,18917,28031,951,12118,3505,2731,13034,30730,6800,3434,2071,16717,6218,8212,165314

In [4]:
df = df[['time_iso8601','sum_deaths']]
df['time_iso8601']= df['time_iso8601'].str.split('T').str[0]
df = df.rename(columns={"time_iso8601": "date", "sum_deaths": "cumDeath"})